spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/SBJ_Project
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    open-in-view: false